/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NnsProposalStatus = IDL.Variant({
  'open' : IDL.Null,
  'rejected' : IDL.Null,
  'executing' : IDL.Null,
  'executed' : IDL.Null,
  'failed' : IDL.Null,
  'adopted' : IDL.Null,
});
export const NnsProposal = IDL.Record({
  'id' : IDL.Nat64,
  'status' : NnsProposalStatus,
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'votesYes' : IDL.Nat64,
  'summary' : IDL.Text,
  'votingPeriodEnd' : IDL.Int,
  'votesNo' : IDL.Nat64,
  'proposer' : IDL.Text,
  'isMission70Related' : IDL.Bool,
});
export const AssetId = IDL.Variant({
  'ADA' : IDL.Null,
  'BTC' : IDL.Null,
  'ETH' : IDL.Null,
  'FET' : IDL.Null,
  'ICP' : IDL.Null,
  'INJ' : IDL.Null,
  'SOL' : IDL.Null,
  'XRP' : IDL.Null,
  'AVAX' : IDL.Null,
});
export const AssetProtocolEvent = IDL.Record({
  'title' : IDL.Text,
  'assetId' : AssetId,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'eventType' : IDL.Text,
});
export const MetricSnapshot = IDL.Record({
  'cycleBurnRateTcycles' : IDL.Float64,
  'icpPrice24hChange' : IDL.Float64,
  'icpPriceUsd' : IDL.Float64,
  'devCommitsWeekly' : IDL.Nat,
  'sentimentScore' : IDL.Float64,
  'totalCanistersDeployed' : IDL.Nat,
  'activeAddressesIsReal' : IDL.Bool,
  'burnRateIsReal' : IDL.Bool,
  'tvlUsd' : IDL.Float64,
  'timestamp' : IDL.Int,
  'activeAddresses7d' : IDL.Nat,
  'activeAddresses24h' : IDL.Nat,
  'activeAddresses30d' : IDL.Nat,
});
export const AssetSnapshot = IDL.Record({
  'sentimentScore' : IDL.Nat,
  'metrics' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'assetId' : AssetId,
  'marketCap' : IDL.Float64,
  'volume24h' : IDL.Float64,
  'priceChange7d' : IDL.Float64,
  'events' : IDL.Vec(AssetProtocolEvent),
  'timestamp' : IDL.Int,
  'priceChange24h' : IDL.Float64,
  'price' : IDL.Float64,
});
export const ProtocolEvent = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'category' : IDL.Variant({
    'other' : IDL.Null,
    'mission70' : IDL.Null,
    'governance' : IDL.Null,
    'chainFusion' : IDL.Null,
  }),
});
export const MetricSignal = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
  'signal' : IDL.Variant({
    'bear' : IDL.Null,
    'bull' : IDL.Null,
    'neutral' : IDL.Null,
  }),
});
export const SentimentBreakdown = IDL.Record({
  'overallScore' : IDL.Float64,
  'drivingFactors' : IDL.Vec(MetricSignal),
});
export const DataSourceStatus = IDL.Record({
  'burnRateLive' : IDL.Bool,
  'activeAddressesLive' : IDL.Bool,
  'proposalsLive' : IDL.Bool,
  'icpPriceLive' : IDL.Bool,
});
export const RefreshResult = IDL.Variant({
  'ok' : IDL.Record({
    'snapshot' : MetricSnapshot,
    'dataSourceStatus' : DataSourceStatus,
  }),
  'err' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getGovernanceProposals' : IDL.Func([], [IDL.Vec(NnsProposal)], ['query']),
  'getGovernanceProposalsByAsset' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AssetProtocolEvent)],
      ['query'],
    ),
  'getLatestSnapshot' : IDL.Func([], [IDL.Opt(MetricSnapshot)], ['query']),
  'getLatestSnapshotByAsset' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AssetSnapshot)],
      ['query'],
    ),
  'getOpenProposals' : IDL.Func([], [IDL.Vec(NnsProposal)], ['query']),
  'getProtocolEvents' : IDL.Func([], [IDL.Vec(ProtocolEvent)], ['query']),
  'getRecentProposals' : IDL.Func([IDL.Nat], [IDL.Vec(NnsProposal)], ['query']),
  'getSentimentBreakdown' : IDL.Func([], [SentimentBreakdown], ['query']),
  'getSnapshotHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MetricSnapshot)],
      ['query'],
    ),
  'getSnapshotHistoryByAsset' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(AssetSnapshot)],
      ['query'],
    ),
  'refreshAllAssets' : IDL.Func([], [], []),
  'refreshAsset' : IDL.Func([IDL.Text], [], []),
  'refreshMetrics' : IDL.Func([], [RefreshResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transform_addresses' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transform_burnrate' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transform_cg_chart' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transform_cg_markets' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transform_proposals' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NnsProposalStatus = IDL.Variant({
    'open' : IDL.Null,
    'rejected' : IDL.Null,
    'executing' : IDL.Null,
    'executed' : IDL.Null,
    'failed' : IDL.Null,
    'adopted' : IDL.Null,
  });
  const NnsProposal = IDL.Record({
    'id' : IDL.Nat64,
    'status' : NnsProposalStatus,
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'votesYes' : IDL.Nat64,
    'summary' : IDL.Text,
    'votingPeriodEnd' : IDL.Int,
    'votesNo' : IDL.Nat64,
    'proposer' : IDL.Text,
    'isMission70Related' : IDL.Bool,
  });
  const AssetId = IDL.Variant({
    'ADA' : IDL.Null,
    'BTC' : IDL.Null,
    'ETH' : IDL.Null,
    'FET' : IDL.Null,
    'ICP' : IDL.Null,
    'INJ' : IDL.Null,
    'SOL' : IDL.Null,
    'XRP' : IDL.Null,
    'AVAX' : IDL.Null,
  });
  const AssetProtocolEvent = IDL.Record({
    'title' : IDL.Text,
    'assetId' : AssetId,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'eventType' : IDL.Text,
  });
  const MetricSnapshot = IDL.Record({
    'cycleBurnRateTcycles' : IDL.Float64,
    'icpPrice24hChange' : IDL.Float64,
    'icpPriceUsd' : IDL.Float64,
    'devCommitsWeekly' : IDL.Nat,
    'sentimentScore' : IDL.Float64,
    'totalCanistersDeployed' : IDL.Nat,
    'activeAddressesIsReal' : IDL.Bool,
    'burnRateIsReal' : IDL.Bool,
    'tvlUsd' : IDL.Float64,
    'timestamp' : IDL.Int,
    'activeAddresses7d' : IDL.Nat,
    'activeAddresses24h' : IDL.Nat,
    'activeAddresses30d' : IDL.Nat,
  });
  const AssetSnapshot = IDL.Record({
    'sentimentScore' : IDL.Nat,
    'metrics' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'assetId' : AssetId,
    'marketCap' : IDL.Float64,
    'volume24h' : IDL.Float64,
    'priceChange7d' : IDL.Float64,
    'events' : IDL.Vec(AssetProtocolEvent),
    'timestamp' : IDL.Int,
    'priceChange24h' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const ProtocolEvent = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'category' : IDL.Variant({
      'other' : IDL.Null,
      'mission70' : IDL.Null,
      'governance' : IDL.Null,
      'chainFusion' : IDL.Null,
    }),
  });
  const MetricSignal = IDL.Record({
    'value' : IDL.Text,
    'name' : IDL.Text,
    'signal' : IDL.Variant({
      'bear' : IDL.Null,
      'bull' : IDL.Null,
      'neutral' : IDL.Null,
    }),
  });
  const SentimentBreakdown = IDL.Record({
    'overallScore' : IDL.Float64,
    'drivingFactors' : IDL.Vec(MetricSignal),
  });
  const DataSourceStatus = IDL.Record({
    'burnRateLive' : IDL.Bool,
    'activeAddressesLive' : IDL.Bool,
    'proposalsLive' : IDL.Bool,
    'icpPriceLive' : IDL.Bool,
  });
  const RefreshResult = IDL.Variant({
    'ok' : IDL.Record({
      'snapshot' : MetricSnapshot,
      'dataSourceStatus' : DataSourceStatus,
    }),
    'err' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getGovernanceProposals' : IDL.Func([], [IDL.Vec(NnsProposal)], ['query']),
    'getGovernanceProposalsByAsset' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AssetProtocolEvent)],
        ['query'],
      ),
    'getLatestSnapshot' : IDL.Func([], [IDL.Opt(MetricSnapshot)], ['query']),
    'getLatestSnapshotByAsset' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AssetSnapshot)],
        ['query'],
      ),
    'getOpenProposals' : IDL.Func([], [IDL.Vec(NnsProposal)], ['query']),
    'getProtocolEvents' : IDL.Func([], [IDL.Vec(ProtocolEvent)], ['query']),
    'getRecentProposals' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(NnsProposal)],
        ['query'],
      ),
    'getSentimentBreakdown' : IDL.Func([], [SentimentBreakdown], ['query']),
    'getSnapshotHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MetricSnapshot)],
        ['query'],
      ),
    'getSnapshotHistoryByAsset' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(AssetSnapshot)],
        ['query'],
      ),
    'refreshAllAssets' : IDL.Func([], [], []),
    'refreshAsset' : IDL.Func([IDL.Text], [], []),
    'refreshMetrics' : IDL.Func([], [RefreshResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transform_addresses' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transform_burnrate' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transform_cg_chart' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transform_cg_markets' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transform_proposals' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };