/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssetId = { 'ADA' : null } |
  { 'BTC' : null } |
  { 'ETH' : null } |
  { 'FET' : null } |
  { 'ICP' : null } |
  { 'INJ' : null } |
  { 'SOL' : null } |
  { 'XRP' : null } |
  { 'AVAX' : null };
export interface AssetProtocolEvent {
  'title' : string,
  'assetId' : AssetId,
  'description' : string,
  'timestamp' : bigint,
  'eventType' : string,
}
export interface AssetSnapshot {
  'sentimentScore' : bigint,
  'metrics' : Array<[string, number]>,
  'assetId' : AssetId,
  'marketCap' : number,
  'volume24h' : number,
  'priceChange7d' : number,
  'events' : Array<AssetProtocolEvent>,
  'timestamp' : bigint,
  'priceChange24h' : number,
  'price' : number,
}
export interface DataSourceStatus {
  'burnRateLive' : boolean,
  'activeAddressesLive' : boolean,
  'proposalsLive' : boolean,
  'icpPriceLive' : boolean,
}
export interface MetricSignal {
  'value' : string,
  'name' : string,
  'signal' : { 'bear' : null } |
    { 'bull' : null } |
    { 'neutral' : null },
}
export interface MetricSnapshot {
  'cycleBurnRateTcycles' : number,
  'icpPrice24hChange' : number,
  'icpPriceUsd' : number,
  'devCommitsWeekly' : bigint,
  'sentimentScore' : number,
  'totalCanistersDeployed' : bigint,
  'activeAddressesIsReal' : boolean,
  'burnRateIsReal' : boolean,
  'tvlUsd' : number,
  'timestamp' : bigint,
  'activeAddresses7d' : bigint,
  'activeAddresses24h' : bigint,
  'activeAddresses30d' : bigint,
}
export interface NnsProposal {
  'id' : bigint,
  'status' : NnsProposalStatus,
  'title' : string,
  'topic' : string,
  'votesYes' : bigint,
  'summary' : string,
  'votingPeriodEnd' : bigint,
  'votesNo' : bigint,
  'proposer' : string,
  'isMission70Related' : boolean,
}
export type NnsProposalStatus = { 'open' : null } |
  { 'rejected' : null } |
  { 'executing' : null } |
  { 'executed' : null } |
  { 'failed' : null } |
  { 'adopted' : null };
export interface ProtocolEvent {
  'title' : string,
  'date' : string,
  'category' : { 'other' : null } |
    { 'mission70' : null } |
    { 'governance' : null } |
    { 'chainFusion' : null },
}
export type RefreshResult = {
    'ok' : {
      'snapshot' : MetricSnapshot,
      'dataSourceStatus' : DataSourceStatus,
    }
  } |
  { 'err' : string };
export interface SentimentBreakdown {
  'overallScore' : number,
  'drivingFactors' : Array<MetricSignal>,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'getGovernanceProposals' : ActorMethod<[], Array<NnsProposal>>,
  'getGovernanceProposalsByAsset' : ActorMethod<
    [string],
    Array<AssetProtocolEvent>
  >,
  'getLatestSnapshot' : ActorMethod<[], [] | [MetricSnapshot]>,
  'getLatestSnapshotByAsset' : ActorMethod<[string], [] | [AssetSnapshot]>,
  'getOpenProposals' : ActorMethod<[], Array<NnsProposal>>,
  'getProtocolEvents' : ActorMethod<[], Array<ProtocolEvent>>,
  'getRecentProposals' : ActorMethod<[bigint], Array<NnsProposal>>,
  'getSentimentBreakdown' : ActorMethod<[], SentimentBreakdown>,
  'getSnapshotHistory' : ActorMethod<[bigint], Array<MetricSnapshot>>,
  'getSnapshotHistoryByAsset' : ActorMethod<
    [string, bigint],
    Array<AssetSnapshot>
  >,
  'refreshAllAssets' : ActorMethod<[], undefined>,
  'refreshAsset' : ActorMethod<[string], undefined>,
  'refreshMetrics' : ActorMethod<[], RefreshResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transform_addresses' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transform_burnrate' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transform_cg_chart' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transform_cg_markets' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transform_proposals' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];