/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SentimentBreakdown {
    overallScore: number;
    drivingFactors: Array<MetricSignal>;
}
export interface AssetSnapshot {
    sentimentScore: bigint;
    metrics: Array<[string, number]>;
    assetId: AssetId;
    marketCap: number;
    volume24h: number;
    priceChange7d: number;
    events: Array<AssetProtocolEvent>;
    timestamp: bigint;
    priceChange24h: number;
    price: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type RefreshResult = {
    __kind__: "ok";
    ok: {
        snapshot: MetricSnapshot;
        dataSourceStatus: DataSourceStatus;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface AssetProtocolEvent {
    title: string;
    assetId: AssetId;
    description: string;
    timestamp: bigint;
    eventType: string;
}
export interface MetricSignal {
    value: string;
    name: string;
    signal: Variant_bear_bull_neutral;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ProtocolEvent {
    title: string;
    date: string;
    category: Variant_other_mission70_governance_chainFusion;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface MetricSnapshot {
    cycleBurnRateTcycles: number;
    icpPrice24hChange: number;
    icpPriceUsd: number;
    devCommitsWeekly: bigint;
    sentimentScore: number;
    totalCanistersDeployed: bigint;
    activeAddressesIsReal: boolean;
    burnRateIsReal: boolean;
    tvlUsd: number;
    timestamp: bigint;
    activeAddresses7d: bigint;
    activeAddresses24h: bigint;
    activeAddresses30d: bigint;
}
export interface DataSourceStatus {
    burnRateLive: boolean;
    activeAddressesLive: boolean;
    proposalsLive: boolean;
    icpPriceLive: boolean;
}
export interface NnsProposal {
    id: bigint;
    status: NnsProposalStatus;
    title: string;
    topic: string;
    votesYes: bigint;
    summary: string;
    votingPeriodEnd: bigint;
    votesNo: bigint;
    proposer: string;
    isMission70Related: boolean;
}
export enum AssetId {
    ADA = "ADA",
    BTC = "BTC",
    ETH = "ETH",
    FET = "FET",
    ICP = "ICP",
    INJ = "INJ",
    SOL = "SOL",
    XRP = "XRP",
    AVAX = "AVAX"
}
export enum NnsProposalStatus {
    open = "open",
    rejected = "rejected",
    executing = "executing",
    executed = "executed",
    failed = "failed",
    adopted = "adopted"
}
export enum Variant_bear_bull_neutral {
    bear = "bear",
    bull = "bull",
    neutral = "neutral"
}
export enum Variant_other_mission70_governance_chainFusion {
    other = "other",
    mission70 = "mission70",
    governance = "governance",
    chainFusion = "chainFusion"
}
export interface backendInterface {
    getGovernanceProposals(): Promise<Array<NnsProposal>>;
    getGovernanceProposalsByAsset(assetId: string): Promise<Array<AssetProtocolEvent>>;
    getLatestSnapshot(): Promise<MetricSnapshot | null>;
    getLatestSnapshotByAsset(assetId: string): Promise<AssetSnapshot | null>;
    getOpenProposals(): Promise<Array<NnsProposal>>;
    getProtocolEvents(): Promise<Array<ProtocolEvent>>;
    getRecentProposals(limit: bigint): Promise<Array<NnsProposal>>;
    getSentimentBreakdown(): Promise<SentimentBreakdown>;
    getSnapshotHistory(days: bigint): Promise<Array<MetricSnapshot>>;
    getSnapshotHistoryByAsset(assetId: string, limit: bigint): Promise<Array<AssetSnapshot>>;
    refreshAllAssets(): Promise<void>;
    refreshAsset(assetIdText: string): Promise<void>;
    refreshMetrics(): Promise<RefreshResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    transform_addresses(input: TransformationInput): Promise<TransformationOutput>;
    transform_burnrate(input: TransformationInput): Promise<TransformationOutput>;
    transform_cg_chart(input: TransformationInput): Promise<TransformationOutput>;
    transform_cg_markets(input: TransformationInput): Promise<TransformationOutput>;
    transform_proposals(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AssetId as _AssetId, AssetProtocolEvent as _AssetProtocolEvent, AssetSnapshot as _AssetSnapshot, DataSourceStatus as _DataSourceStatus, MetricSignal as _MetricSignal, MetricSnapshot as _MetricSnapshot, NnsProposal as _NnsProposal, NnsProposalStatus as _NnsProposalStatus, ProtocolEvent as _ProtocolEvent, RefreshResult as _RefreshResult, SentimentBreakdown as _SentimentBreakdown } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getGovernanceProposals(): Promise<Array<NnsProposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGovernanceProposals();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGovernanceProposals();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGovernanceProposalsByAsset(arg0: string): Promise<Array<AssetProtocolEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGovernanceProposalsByAsset(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGovernanceProposalsByAsset(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestSnapshot(): Promise<MetricSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestSnapshot();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestSnapshot();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestSnapshotByAsset(arg0: string): Promise<AssetSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestSnapshotByAsset(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestSnapshotByAsset(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenProposals(): Promise<Array<NnsProposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenProposals();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenProposals();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProtocolEvents(): Promise<Array<ProtocolEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProtocolEvents();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProtocolEvents();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentProposals(arg0: bigint): Promise<Array<NnsProposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentProposals(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentProposals(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSentimentBreakdown(): Promise<SentimentBreakdown> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentimentBreakdown();
                return from_candid_SentimentBreakdown_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentimentBreakdown();
            return from_candid_SentimentBreakdown_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSnapshotHistory(arg0: bigint): Promise<Array<MetricSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSnapshotHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSnapshotHistory(arg0);
            return result;
        }
    }
    async getSnapshotHistoryByAsset(arg0: string, arg1: bigint): Promise<Array<AssetSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSnapshotHistoryByAsset(arg0, arg1);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSnapshotHistoryByAsset(arg0, arg1);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async refreshAllAssets(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshAllAssets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshAllAssets();
            return result;
        }
    }
    async refreshAsset(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshAsset(arg0);
            return result;
        }
    }
    async refreshMetrics(): Promise<RefreshResult> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshMetrics();
                return from_candid_RefreshResult_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshMetrics();
            return from_candid_RefreshResult_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async transform_addresses(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform_addresses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform_addresses(arg0);
            return result;
        }
    }
    async transform_burnrate(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform_burnrate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform_burnrate(arg0);
            return result;
        }
    }
    async transform_cg_chart(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform_cg_chart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform_cg_chart(arg0);
            return result;
        }
    }
    async transform_cg_markets(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform_cg_markets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform_cg_markets(arg0);
            return result;
        }
    }
    async transform_proposals(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform_proposals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform_proposals(arg0);
            return result;
        }
    }
}
function from_candid_AssetId_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetId): AssetId {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_AssetProtocolEvent_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetProtocolEvent): AssetProtocolEvent {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_AssetSnapshot_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetSnapshot): AssetSnapshot {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MetricSignal_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MetricSignal): MetricSignal {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_NnsProposalStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NnsProposalStatus): NnsProposalStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_NnsProposal_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NnsProposal): NnsProposal {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ProtocolEvent_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProtocolEvent): ProtocolEvent {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_RefreshResult_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RefreshResult): RefreshResult {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_SentimentBreakdown_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SentimentBreakdown): SentimentBreakdown {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MetricSnapshot]): MetricSnapshot | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssetSnapshot]): AssetSnapshot | null {
    return value.length === 0 ? null : from_candid_AssetSnapshot_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sentimentScore: bigint;
    metrics: Array<[string, number]>;
    assetId: _AssetId;
    marketCap: number;
    volume24h: number;
    priceChange7d: number;
    events: Array<_AssetProtocolEvent>;
    timestamp: bigint;
    priceChange24h: number;
    price: number;
}): {
    sentimentScore: bigint;
    metrics: Array<[string, number]>;
    assetId: AssetId;
    marketCap: number;
    volume24h: number;
    priceChange7d: number;
    events: Array<AssetProtocolEvent>;
    timestamp: bigint;
    priceChange24h: number;
    price: number;
} {
    return {
        sentimentScore: value.sentimentScore,
        metrics: value.metrics,
        assetId: from_candid_AssetId_n9(_uploadFile, _downloadFile, value.assetId),
        marketCap: value.marketCap,
        volume24h: value.volume24h,
        priceChange7d: value.priceChange7d,
        events: from_candid_vec_n6(_uploadFile, _downloadFile, value.events),
        timestamp: value.timestamp,
        priceChange24h: value.priceChange24h,
        price: value.price
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: string;
    category: {
        other: null;
    } | {
        mission70: null;
    } | {
        governance: null;
    } | {
        chainFusion: null;
    };
}): {
    title: string;
    date: string;
    category: Variant_other_mission70_governance_chainFusion;
} {
    return {
        title: value.title,
        date: value.date,
        category: from_candid_variant_n18(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    overallScore: number;
    drivingFactors: Array<_MetricSignal>;
}): {
    overallScore: number;
    drivingFactors: Array<MetricSignal>;
} {
    return {
        overallScore: value.overallScore,
        drivingFactors: from_candid_vec_n21(_uploadFile, _downloadFile, value.drivingFactors)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: string;
    name: string;
    signal: {
        bear: null;
    } | {
        bull: null;
    } | {
        neutral: null;
    };
}): {
    value: string;
    name: string;
    signal: Variant_bear_bull_neutral;
} {
    return {
        value: value.value,
        name: value.name,
        signal: from_candid_variant_n24(_uploadFile, _downloadFile, value.signal)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _NnsProposalStatus;
    title: string;
    topic: string;
    votesYes: bigint;
    summary: string;
    votingPeriodEnd: bigint;
    votesNo: bigint;
    proposer: string;
    isMission70Related: boolean;
}): {
    id: bigint;
    status: NnsProposalStatus;
    title: string;
    topic: string;
    votesYes: bigint;
    summary: string;
    votingPeriodEnd: bigint;
    votesNo: bigint;
    proposer: string;
    isMission70Related: boolean;
} {
    return {
        id: value.id,
        status: from_candid_NnsProposalStatus_n4(_uploadFile, _downloadFile, value.status),
        title: value.title,
        topic: value.topic,
        votesYes: value.votesYes,
        summary: value.summary,
        votingPeriodEnd: value.votingPeriodEnd,
        votesNo: value.votesNo,
        proposer: value.proposer,
        isMission70Related: value.isMission70Related
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    assetId: _AssetId;
    description: string;
    timestamp: bigint;
    eventType: string;
}): {
    title: string;
    assetId: AssetId;
    description: string;
    timestamp: bigint;
    eventType: string;
} {
    return {
        title: value.title,
        assetId: from_candid_AssetId_n9(_uploadFile, _downloadFile, value.assetId),
        description: value.description,
        timestamp: value.timestamp,
        eventType: value.eventType
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ADA: null;
} | {
    BTC: null;
} | {
    ETH: null;
} | {
    FET: null;
} | {
    ICP: null;
} | {
    INJ: null;
} | {
    SOL: null;
} | {
    XRP: null;
} | {
    AVAX: null;
}): AssetId {
    return "ADA" in value ? AssetId.ADA : "BTC" in value ? AssetId.BTC : "ETH" in value ? AssetId.ETH : "FET" in value ? AssetId.FET : "ICP" in value ? AssetId.ICP : "INJ" in value ? AssetId.INJ : "SOL" in value ? AssetId.SOL : "XRP" in value ? AssetId.XRP : "AVAX" in value ? AssetId.AVAX : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    mission70: null;
} | {
    governance: null;
} | {
    chainFusion: null;
}): Variant_other_mission70_governance_chainFusion {
    return "other" in value ? Variant_other_mission70_governance_chainFusion.other : "mission70" in value ? Variant_other_mission70_governance_chainFusion.mission70 : "governance" in value ? Variant_other_mission70_governance_chainFusion.governance : "chainFusion" in value ? Variant_other_mission70_governance_chainFusion.chainFusion : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bear: null;
} | {
    bull: null;
} | {
    neutral: null;
}): Variant_bear_bull_neutral {
    return "bear" in value ? Variant_bear_bull_neutral.bear : "bull" in value ? Variant_bear_bull_neutral.bull : "neutral" in value ? Variant_bear_bull_neutral.neutral : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        snapshot: _MetricSnapshot;
        dataSourceStatus: _DataSourceStatus;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        snapshot: MetricSnapshot;
        dataSourceStatus: DataSourceStatus;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    open: null;
} | {
    rejected: null;
} | {
    executing: null;
} | {
    executed: null;
} | {
    failed: null;
} | {
    adopted: null;
}): NnsProposalStatus {
    return "open" in value ? NnsProposalStatus.open : "rejected" in value ? NnsProposalStatus.rejected : "executing" in value ? NnsProposalStatus.executing : "executed" in value ? NnsProposalStatus.executed : "failed" in value ? NnsProposalStatus.failed : "adopted" in value ? NnsProposalStatus.adopted : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NnsProposal>): Array<NnsProposal> {
    return value.map((x)=>from_candid_NnsProposal_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProtocolEvent>): Array<ProtocolEvent> {
    return value.map((x)=>from_candid_ProtocolEvent_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MetricSignal>): Array<MetricSignal> {
    return value.map((x)=>from_candid_MetricSignal_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssetSnapshot>): Array<AssetSnapshot> {
    return value.map((x)=>from_candid_AssetSnapshot_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssetProtocolEvent>): Array<AssetProtocolEvent> {
    return value.map((x)=>from_candid_AssetProtocolEvent_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
